name: decrypt-dotenv-vault
description: 'Decrypts a .env.vault file using dotenv-vault'
branding:
  icon: 'lock'
  color: 'green'
inputs:
  dotenv-key:
    description: 'The dotenv-vault encryption key'
    required: true
  env-file:
    description: 'The name of the environment file to generate'
    required: false
    default: '.env.ci'
  node-version:
    description: 'The version of Node.js to use'
    required: false
    default: '20'
  node-version-file:
    description: 'The path to a file containing the version of Node.js to use'
    required: false
  architecture:
    description: 'The architecture of Node.js to use (x86 or x64)'
    required: false
  check-latest:
    description: 'Set to true to check for the latest available version of Node.js'
    required: false
  registry-url:
    description: 'The base URL of the npm registry'
    required: false
  scope:
    description: 'The scope of the npm registry'
    required: false
  token:
    description: 'The token to use for authentication with the npm registry'
    required: false
  always-auth:
    description: 'Set always-auth option in npmrc file'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version-file }}
        architecture: ${{ inputs.architecture }}
        check-latest: ${{ inputs.check-latest }}
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
        token: ${{ inputs.token }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm i --prefer-offline --no-audit
      shell: bash
    - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install dependencies if needed
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
   
    - name: Decrypt .env.vault
      run: npx dotenv-vault decrypt ${{ inputs.dotenv-key }} > ${{ inputs.env-file }}
      shell: bash
